### ISSUE TITLE
extra lifes dont work

### ISSUE THREAD

**Issue by romkacaddy** [apipy/HQApi#18]
`def life(wss, question):
	wss.send_life(question)`

life isnt reduced and messages from the websocket arent received
//
but i can send answers

`def send_ans(ws, answerid, questionid):
	ws.send_answer(answerid, questionid)`

### 

### base64
`0YXRgNC40YHRgtC+0YEg0LLQvtGB0LrRgNC10YHQtQ==`

**Comment by katant** [comment]
Are they worked before?

**Comment by romkacaddy** [comment]
нет. не юзал.

**Comment by katant** [comment]
Уверен что передаешь верный question id?

**Comment by romkacaddy** [comment]
уверен.

**Comment by romkacaddy** [comment]
всю инфу о вопросе и его ответах записываю в словарь

**Comment by romkacaddy** [comment]
все разобрался. это я дебил. возможно и получение ерасеров тоже не работает из-за того что ты принимаешь словарь. а не список

**Comment by katant** [comment]
> принимаешь словарь. а не список
Исправил

**Comment by katant** [comment]
Если не заработает - открой ещё раз.
