### ISSUE TITLE
Erasers

### ISSUE THREAD

**Issue by 12135555** [apipy/HQApi#19]
Does getting erasers working? I added 3 accounts in friends to each other and used "get_erasers" method on a live game, but nothing happened.

**Comment by romkacaddy** [comment]
та же самая проблема.

**Comment by 12135555** [comment]
> та же самая проблема.
> i've got some problem

Most likely they changed JSON to get them. Previously, there existed a discord bot which made it possible to get erasers, but now it does not work. I wrote in their support and they replied that HQ improved the protection for getting erasers.
