### ISSUE TITLE
How to connect live game

### ISSUE THREAD

**Issue by sourovafrin** [apipy/HQApi#21]
How can i connect to live games?

**Comment by katant** [comment]
Check websocket.py and websocket_event.py in examples. If you want to connect only to HQ websocket, set demo to False.

**Comment by sourovafrin** [comment]
```
ws = HQWebSocket(api, demo=True)
ws.listen()


@ws.event("interaction")
def interaction(data):
    print("Interaction: " + str(data))
 ```

Can i join the game by this code? the game requires join to the live game to get live from refer. Will i get live?

**Comment by katant** [comment]
Remove demo=True
