### ISSUE TITLE
How to use ur api to connect and get eraser?

### ISSUE THREAD

**Issue by Bpsingh5** [apipy/HQApi#23]
JSON to get erasers:

api = HQApi(token1)
ws = HQWebSocket(api, demo=True)
ws.listen()
@ws.event("interaction")
def interaction(data):
    fried = '26110182'
    a = ws.get_erasers(fried)

    print(a)
 print is None

Can u help me in this @katant

**Comment by malay1234456** [comment]
I guess hq changed the json format

**Comment by katant** [comment]
At first, all websocket methods return None. You need to provide list, not string, so you need 2 friends ids and they changed method for getting erasers
