### ISSUE TITLE
Ваш Api полностью обновлен?

### ISSUE THREAD

**Issue by ragor11** [apipy/HQApi#24]
Эй, Роджер, я тоже из России, я хочу знать, обновлен ли твой HQAPI, потому что я использую что-то в ластике, но я думаю, что HQ изменил свой метод Можете ли вы помочь мне в этом?

**Comment by katant** [comment]
Тут Роджера нету, если ты ко мне, давай поговорим. А из какого ты города? Я просто впервые вижу русских в internet. А и ластик запихни себе в очко

**Comment by katant** [comment]
Блин зачем ты ему очко закрыл((((
