### ISSUE TITLE
I made hq lives bot while joining game for account error came anyone can solve

### ISSUE THREAD

**Issue by chetanchetu1728** [apipy/HQApi#27]
self.run()2019-12-16T01:58:46.020697+00:00 app[worker.1]: File "/app/HQApi/hq_websocket.py", line 196, in run2019-12-16T01:58:46.020700+00:00 app[worker.1]: self.new.call({"type": data["type"], "data": data})

**Comment by katant** [comment]
Can you give full traceback from python?

**Comment by chetanchetu1728** [comment]
> Can you give full traceback from python?

Sir it is showing that key error 'type'
disconnecting websocket
Exception in thread Thread-353:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\lifebot\HQApi\hq_websocket.py", line 196, in run
    self.new.call({"type": data["type"], "data": data})
KeyError: 'type'

It means Lifebot was unable to join game 
I have changed to except then also error is coming error' 'not authorized' 'error code' 102
Can u give new IP I think ip banned

**Comment by katant** [comment]
> > Can you give full traceback from python?
> 
> Sir it is showing that key error 'type'
> disconnecting websocket
> Exception in thread Thread-353:
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
> self.run()
> File "C:\Users\Administrator\Desktop\lifebot\HQApi\hq_websocket.py", line 196, in run
> self.new.call({"type": data["type"], "data": data})
> KeyError: 'type'
> 
> It means Lifebot was unable to join game
> I have changed to except then also error is coming error' 'not authorized' 'error code' 102
> Can u give new IP I think ip banned

Your account is banned.
