### ISSUE TITLE
HQ Account bans

### ISSUE THREAD

**Issue by harisai1001** [apipy/HQApi#32]
HQ accounts are getting banned is there any solution for it 
If we change some stuff in HQ api can we solve this problem @katant

**Comment by katant** [comment]
**HQApi is unmaintained.** 

Which HQ version are you using with HQApi? How many accounts you run on one IP?

**Comment by harisai1001** [comment]
Latest version only 
4 accs for 1 proxy i am using

**Comment by harisai1001** [comment]
![IMG_20200728_194041](https://user-images.githubusercontent.com/66504100/88708900-fe673200-d131-11ea-99f5-d89e504bfbbf.jpg)
I am getting this error when i used ur offair trivia code i mean to play daily challenges

**Comment by harisai1001** [comment]
I already messaged u in telegram but u didnt respond to it 🤧🤧 i want to discuss about HQ 
 💧💧   💧   💧💧💧 water...

**Comment by katant** [comment]
> 4 accs for 1 proxy i am using
You should use 1 account per proxy. And avoid new versions. Use 1.49.8
