### ISSUE TITLE
Hq lives

### ISSUE THREAD

**Issue by mahihugar** [apipy/HQApi#34]

**Comment by mahihugar** [comment]
Need hq lives script pls

**Comment by vvettoretti** [comment]
Need script to get a girlfriend pls

**Comment by katant** [comment]
Need free money script pls

**Comment by Nothecaptain** [comment]
Need free robux script plz

**Comment by mahihugar** [comment]
Can I get hq lives script pls

**Comment by katant** [comment]
> Can I get hq lives script pls

No, you can't

**Comment by vvettoretti** [comment]
Can i get girlfriend script pls

**Comment by mahihugar** [comment]
Fuck off
