### ISSUE TITLE
api not accepting token - HQApi.exceptions.ApiResponseError: {"error": "invalid token", "errorCode": 406}

### ISSUE THREAD

**Issue by mme56976** [apipy/HQApi#35]
**Warning**
Make sure you aren't asking for anything. For example, don't ask any bot sources, info, links or etc. HQApi is HQ Trivia API wrapper, not page to discuss HQ questions. You can discuss HQ at our telegram group: https://t.me/hqapi

**Describe the bug**
I get a "HQApi.exceptions.ApiResponseError: {"error": "invalid token", "errorCode": 406}" when trying to use my token to use the api, even though my token is correct.

**Expected behavior**
The expected behavior would be for the api to accept my token and return info from HQ.

**Desktop (please complete the following information):**
 - Python version: [3.8.5]
 - HQApi version [2.5.1]
 - HQ Version in HQApi [1.49.8]

**Additional context**
The api was working fine yesterday. The issue isn't the token itself. I tried two different tokens with the api, neither worked. But when using a phone and the actual HQ app, the accounts which used those tokens were able to play the game. Maybe it's possible that HQ changed the content/header information it needs when receiving a request. Sorry for not explaining the issue well, I'm fairly new at Python.

Here is the exact error message:

```
Traceback (most recent call last):
  File "C:\Users\---\Desktop\---\test.py", line 18, in test
    api = HQApi(login_token='MY_TOKEN')
  File "C:\Users\---\Desktop\---\HQApi\hq_api.py", line 150, in __init__
    self.token = self.get_tokens(login_token)["accessToken"]
  File "C:\Users\---\Desktop\---\HQApi\hq_api.py", line 74, in get_tokens
    return self.fetch("POST", "tokens", {'token': login_token})
  File "C:\Users\---\Desktop\---\HQApi\hq_api.py", line 187, in fetch
    raise ApiResponseError(json.dumps(content))
HQApi.exceptions.ApiResponseError: {"error": "invalid token", "errorCode": 406}
```

And here is the segment of code I'm trying to run:

```
from HQApi import HQApi

api = HQApi(login_token='MY_TOKEN')

print(api.get_users_me())
```

**Comment by mme56976** [comment]
I think I've narrowed down the exact line it seems to fail at in hq_api.py in the method `def fetch(self, method="GET", func="", data=None, files=None):`

```
if method == "GET":
            content = self.session.get(self.host + "{}".format(func), data=data,
                                       headers=self.headers, proxies=self.p, verify=self.v).json()
```

After this line, it raises an exception.

**Comment by katant** [comment]
Check again that you are using LOGIN token, not auth/access token.
Login token looks like:
```uQOOiASmugQh2F09qj39LO1DaWUf7bkSeUn4ofHQJl7dcgzNPzReI1aAHmm0Kgwc```
And access/auth is like:
```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0NjA1NTgyLCJ1c2VybmFtZSI6IkhRQXBpd2VsIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9jZG4ucHJvZC5oeXBlLnNwYWNlL2EvMjQ2MDU1ODItdTR2dXZaIiwidG9rZW4iOiJ1UU9PaUEiLCJyb2xlcyI6W10sImNsaWVudCI6IkFuZHJvaWQvMS40OS44IiwiZ3Vlc3RJZCI6bnVsbCwidiI6MSwiaWF0IjoxNjAxMDk2MzAwLCJleHAiOjE2MDg4NzIzMDAsImlzcyI6Imh5cGVxdWl6LzEifQ.bg0Y6KqKb82FRfDCfLZmNUy4YfJZxU2u2S9cxvqj5Xo``` 
If you are using access token, use:
```api = HQApi(token='MY_TOKEN')```

**Comment by mme56976** [comment]
I was using the access/auth token. I switched the code segment to this:

```
from HQApi import HQApi

api = HQApi(token='MY_AUTH_TOKEN')

print(api.get_users_me())
```

But I'm now getting this error:

```
Traceback (most recent call last):
  File "C:\Users\---\Desktop\---\triv.py", line 20, in test
    print(api.get_users_me())
  File "C:\Users\---\Desktop\---\HQApi\hq_api.py", line 16, in get_users_me
    return self.fetch("GET", "users/me")
  File "C:\Users\---\Desktop\---\HQApi\hq_api.py", line 193, in fetch
    raise ApiResponseError(json.dumps(content))
HQApi.exceptions.ApiResponseError: {"error": "Auth not valid", "errorCode": 105}
```

For extra context, after: 

```
if method == "GET":
            content = self.session.get(self.host + "{}".format(func), data=data,
                                       headers=self.headers, proxies=self.p, verify=self.v).json()
```

content is:

_{'error': 'Auth not valid', 'errorCode': 105}_

**Comment by katant** [comment]
Your token is invalid
