### ISSUE TITLE
No code sent by bot

### ISSUE THREAD

**Issue by aamit2267** [apipy/HQApi#36]
**Warning**
Make sure you aren't asking for anything. For example, don't ask any bot sources, info, links or etc. HQApi is HQ Trivia API wrapper, not page to discuss HQ questions. You can discuss HQ at our telegram group: https://t.me/hqapi

**Describe the bug**

**Expected behavior**

**Desktop (please complete the following information):**
 - Python version: [e.g. 3.8.5]
 - HQApi version [e.g. 2.5.1]
 - HQ Version in HQApi [e.g. 1.49.8]

**Additional context**

**Comment by aamit2267** [comment]
i am trying to pass code to the number but its not sending the code.

**Comment by katant** [comment]
Invalid issue

**Comment by aamit2267** [comment]
i got to know that there is an error IP banned
