### ISSUE TITLE
Hq sports api

### ISSUE THREAD

**Issue by rahul5544** [apipy/HQApi#43]
Can I get the hq sports api

**Comment by katant** [comment]
HQ Sports is available via regular API

**Comment by rahul5544** [comment]
Can u give me little instruction how to connect with hq sports

**Comment by katant** [comment]
> Can u give me little instruction how to connect with hq sports

Like any other game

**Comment by rahul5544** [comment]
How to use this ???

**Comment by katant** [comment]
> How to use this ???

Check examples and stop asking stupid answers
